# This file is called as an include for all esp01 relay modules
esp8266:
  board: esp01_1m

# Of course, every configuration needs a name.  My configurations use a substititons element before this file is included.
esphome:
  name: ${device_name}

# I'm _really_ happy to have discovered this!  I can develop at home or at my local makerspace and then plop right into one of the other environments.
# There is no evidence that having multiple networks takes any longer for the device to connect - more likely than not, it adds a millisecond or so.
wifi:
  networks: 
    - ssid: !secret ssid_work
      password: !secret password_work
    - ssid: !secret ssid_home
      password: !secret password_home
    - ssid: !secret ssid_makerspace
      password: !secret password_makerspace

  # Just in case, I want the configuration to start the access point so I can connect directly
  ap:
    ssid: "${device_name} Hotspot"
    password: !secret wifi_password

  # I want the ESP to display the log so I can troubleshoot as I am figuring out new features
logger:
#  logs:

# I see no reason to give every single device a different API key.
# Additionally, since I flash most devices from my laptop instead of the HA host system, it'd be even more awkward to keep API keys straight.
api:
  encryption:
    key: !secret api_key

# Like the API key, I see no need to have a different key for OTA updates 
ota:
  password: !secret ota_password

# The web server lets me test many functions without creating an entity in Home Assistant, which is _very_ inconvenient to delete.
web_server:
  port: 80

# Just in case it can't connect to WiFi, make it easy to interface with the configuration.
captive_portal:
  
