# This configuration controls two Bluetooth-controllable RGB flood lights from Neewer.  I was never satisfied with the phone app, which asked if I wanted to use their cloud service (for Bluetooth devices), and would take a couple of minutes
# to connect to the lights.  By using this configuration, I haven't had to wait more than about a second for the lights to respond.
# I plan to eventually create some transitions so that the lights shift through different colors as the class goes on.  
# I'm not sure if the configuration is fast enough to be music-responsive, but that'd be cool.

substitutions:
  device_name: "neewer"
  friendly_name: "Neewer"
  transition: "10" # This is here just in case, to support color shifting.  Right now, we're just turning the lights on or off, and setting a static color which doesn't really need a transition.

# Include the file with my typical settings
<<: !include esp32-basic.yaml

# This is a beautiful project I found that does all the hard work of dissecting and recreating the Bluetooth communication with the Neewer lights.
# With this line, I can include all that code without having to maintain a copy locally.  I have chosen to "hard code" the version since it does everything I want it to and don't want to risk breakage.
external_components:
- source: github://litui/esphome-components@v1.0.0
  #components: [ neewerlight_ble, neewerlight ]  # Including neewerlight_ble allows scanning for Neewer lights via Bluetooth.  I left this here to remind me that if we get new ones, I need to re scan
  components: [ neewerlight ]  # Not including neewerlight_ble when I don't need it keeps the firmware for the ESP32 more lean.

ble_client:  # This is how each light is uniquely identified
- mac_address: D9:3E:CB:2C:26:19
  id: neewer_led_inner

- mac_address: F7:04:C3:96:AE:29
  id: neewer_led_outer

light:
  # This is the declaration of the light at the rear of the classroom which is furthest from the outside wall
  - platform: neewerlight
    name: "Rear Inner Neewer Flood"
    ble_client_id: neewer_led_inner
    gamma_correct: 1.0
    default_transition_length: ${transition}ms
    icon: mdi:ceiling-fan-light
    restore_mode: RESTORE_DEFAULT_OFF

  # This is the declaration of the light at the rear of the classroom which is closest to the outside wall
  - platform: neewerlight
    name: "Rear Outer Neewer Flood"
    ble_client_id: neewer_led_outer
    gamma_correct: 1.0
    default_transition_length: ${transition}ms
    icon: mdi:ceiling-fan-light
    restore_mode: RESTORE_DEFAULT_OFF


